version: '2'
services:
    sms-app:
        image: sms
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://sms-postgresql:5432/SMS
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sms-postgresql:
        extends:
            file: postgresql.yml
            service: sms-postgresql
